server:
  port: 80
  tomcat:
    max-threads: 10
    min-spare-threads: 10



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/footprint?useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      username: root
      password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  resources:
    static-locations: classpath:/static/,classpath:/views/
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    com.stone.generator.dao: debug