server:
  port: 80
  tomcat:
    max-threads: 10
    min-spare-threads: 10



spring:
  datasource:
    url: jdbc:mysql://10.244.76.11:3306/wind_platform?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      username: root
      password: QFIZsy_gNEcd8wAeHV8t9vXgB1AN_ruH

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  resources:
    static-locations: classpath:/static/,classpath:/views/

  generator:
    package-name: com.xyd
    module-name: filesystem


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    com.stone.generator.dao: debug